version: '3.7'
services:
    frontend-relevebancaire:
        image: frontend-relevebancaire
        container_name: "frontend-relevebancaire"
        ports:
        - "4200:4200"
        deploy:
            resources:
                limits:
                    cpus: 0.50
                    memory: 400M
